// Code generated by protoc-gen-go. DO NOT EDIT.
// source: topStations.proto

package topStations

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTopStationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopStationsRequest) Reset()         { *m = GetTopStationsRequest{} }
func (m *GetTopStationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopStationsRequest) ProtoMessage()    {}
func (*GetTopStationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_topStations_cc3f67415fc00fb3, []int{0}
}
func (m *GetTopStationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopStationsRequest.Unmarshal(m, b)
}
func (m *GetTopStationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopStationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetTopStationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopStationsRequest.Merge(dst, src)
}
func (m *GetTopStationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopStationsRequest.Size(m)
}
func (m *GetTopStationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopStationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopStationsRequest proto.InternalMessageInfo

type GetTopStationsResponse struct {
	// Station list
	Stations             []*StationStats `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTopStationsResponse) Reset()         { *m = GetTopStationsResponse{} }
func (m *GetTopStationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTopStationsResponse) ProtoMessage()    {}
func (*GetTopStationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_topStations_cc3f67415fc00fb3, []int{1}
}
func (m *GetTopStationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopStationsResponse.Unmarshal(m, b)
}
func (m *GetTopStationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopStationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetTopStationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopStationsResponse.Merge(dst, src)
}
func (m *GetTopStationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTopStationsResponse.Size(m)
}
func (m *GetTopStationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopStationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopStationsResponse proto.InternalMessageInfo

func (m *GetTopStationsResponse) GetStations() []*StationStats {
	if m != nil {
		return m.Stations
	}
	return nil
}

type StationStats struct {
	// The station's ID
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// The station's ask orders total volume
	AskVolume float64 `protobuf:"fixed64,2,opt,name=ask_volume,json=askVolume,proto3" json:"ask_volume,omitempty"`
	// The station's bid orders total volume
	BidVolume float64 `protobuf:"fixed64,3,opt,name=bid_volume,json=bidVolume,proto3" json:"bid_volume,omitempty"`
	// The station's orders total volume
	TotalVolume float64 `protobuf:"fixed64,4,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	// The station's total number of orders
	TotalOrders          int64    `protobuf:"varint,5,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StationStats) Reset()         { *m = StationStats{} }
func (m *StationStats) String() string { return proto.CompactTextString(m) }
func (*StationStats) ProtoMessage()    {}
func (*StationStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_topStations_cc3f67415fc00fb3, []int{2}
}
func (m *StationStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StationStats.Unmarshal(m, b)
}
func (m *StationStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StationStats.Marshal(b, m, deterministic)
}
func (dst *StationStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StationStats.Merge(dst, src)
}
func (m *StationStats) XXX_Size() int {
	return xxx_messageInfo_StationStats.Size(m)
}
func (m *StationStats) XXX_DiscardUnknown() {
	xxx_messageInfo_StationStats.DiscardUnknown(m)
}

var xxx_messageInfo_StationStats proto.InternalMessageInfo

func (m *StationStats) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StationStats) GetAskVolume() float64 {
	if m != nil {
		return m.AskVolume
	}
	return 0
}

func (m *StationStats) GetBidVolume() float64 {
	if m != nil {
		return m.BidVolume
	}
	return 0
}

func (m *StationStats) GetTotalVolume() float64 {
	if m != nil {
		return m.TotalVolume
	}
	return 0
}

func (m *StationStats) GetTotalOrders() int64 {
	if m != nil {
		return m.TotalOrders
	}
	return 0
}

func init() {
	proto.RegisterType((*GetTopStationsRequest)(nil), "topStations.GetTopStationsRequest")
	proto.RegisterType((*GetTopStationsResponse)(nil), "topStations.GetTopStationsResponse")
	proto.RegisterType((*StationStats)(nil), "topStations.StationStats")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TopStationsClient is the client API for TopStations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TopStationsClient interface {
	GetTopStations(ctx context.Context, in *GetTopStationsRequest, opts ...grpc.CallOption) (*GetTopStationsResponse, error)
}

type topStationsClient struct {
	cc *grpc.ClientConn
}

func NewTopStationsClient(cc *grpc.ClientConn) TopStationsClient {
	return &topStationsClient{cc}
}

func (c *topStationsClient) GetTopStations(ctx context.Context, in *GetTopStationsRequest, opts ...grpc.CallOption) (*GetTopStationsResponse, error) {
	out := new(GetTopStationsResponse)
	err := c.cc.Invoke(ctx, "/topStations.TopStations/GetTopStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopStationsServer is the server API for TopStations service.
type TopStationsServer interface {
	GetTopStations(context.Context, *GetTopStationsRequest) (*GetTopStationsResponse, error)
}

func RegisterTopStationsServer(s *grpc.Server, srv TopStationsServer) {
	s.RegisterService(&_TopStations_serviceDesc, srv)
}

func _TopStations_GetTopStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopStationsServer).GetTopStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topStations.TopStations/GetTopStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopStationsServer).GetTopStations(ctx, req.(*GetTopStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TopStations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topStations.TopStations",
	HandlerType: (*TopStationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopStations",
			Handler:    _TopStations_GetTopStations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "topStations.proto",
}

func init() { proto.RegisterFile("topStations.proto", fileDescriptor_topStations_cc3f67415fc00fb3) }

var fileDescriptor_topStations_cc3f67415fc00fb3 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x49, 0xab, 0xa2, 0xa7, 0x63, 0x60, 0x40, 0xad, 0xc3, 0x61, 0xad, 0x08, 0xbd, 0x5a,
	0x70, 0xe2, 0x33, 0x78, 0x39, 0xa8, 0xe2, 0xad, 0xa4, 0x34, 0x8c, 0xd0, 0xae, 0xa7, 0x36, 0x67,
	0xbb, 0x16, 0x9f, 0x40, 0xf0, 0x0d, 0x7c, 0x25, 0x5f, 0xc1, 0x07, 0x91, 0xa6, 0xad, 0xb6, 0x43,
	0xbc, 0x4a, 0xf8, 0xbf, 0x0f, 0x92, 0xf3, 0x1f, 0x38, 0x24, 0x2c, 0xef, 0x49, 0x92, 0xc6, 0xc2,
	0xcc, 0xca, 0x0a, 0x09, 0xb9, 0xd7, 0x8b, 0x26, 0x67, 0x4b, 0xc4, 0x65, 0xae, 0x84, 0x2c, 0xb5,
	0x90, 0x45, 0x81, 0x03, 0x35, 0x3c, 0x81, 0xa3, 0x3b, 0x45, 0x0f, 0xbf, 0x7e, 0xac, 0x9e, 0xd7,
	0xca, 0x50, 0xb8, 0x80, 0xe3, 0x6d, 0x60, 0x4a, 0x2c, 0x8c, 0xe2, 0xb7, 0xb0, 0x6f, 0xda, 0xcc,
	0x67, 0x81, 0x1b, 0x79, 0xf3, 0xd3, 0x59, 0xff, 0x0f, 0xed, 0xa5, 0x3e, 0x4c, 0xfc, 0xa3, 0x86,
	0x1f, 0x0c, 0x46, 0x7d, 0xc4, 0xc7, 0xe0, 0xe8, 0xd4, 0x67, 0x01, 0x8b, 0xdc, 0xd8, 0xd1, 0x29,
	0x9f, 0x02, 0x48, 0x93, 0x3d, 0x6d, 0x30, 0x5f, 0xaf, 0x94, 0xef, 0x04, 0x2c, 0x62, 0xf1, 0x81,
	0x34, 0xd9, 0xa3, 0x0d, 0x6a, 0x9c, 0xe8, 0xb4, 0xc3, 0x6e, 0x83, 0x13, 0x9d, 0xb6, 0xf8, 0x02,
	0x46, 0x84, 0x24, 0xf3, 0x4e, 0xd8, 0xb1, 0x82, 0x67, 0xb3, 0x6d, 0x05, 0xab, 0x54, 0x55, 0xc6,
	0xdf, 0xb5, 0x4f, 0x37, 0xca, 0xc2, 0x46, 0xf3, 0x37, 0x06, 0x5e, 0x6f, 0x66, 0xfe, 0xc2, 0x60,
	0x3c, 0xac, 0x81, 0x87, 0x83, 0x61, 0xff, 0x2c, 0x6f, 0x72, 0xf9, 0xaf, 0xd3, 0xf4, 0x18, 0x5e,
	0xbd, 0x7e, 0x7e, 0xbd, 0x3b, 0xe7, 0x7c, 0x2a, 0x36, 0xd7, 0x62, 0x25, 0xab, 0x4c, 0x91, 0xa8,
	0xdb, 0x32, 0xa2, 0xeb, 0x4c, 0x10, 0x96, 0xc9, 0x9e, 0x5d, 0xd4, 0xcd, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x24, 0x0a, 0x59, 0x0d, 0xe8, 0x01, 0x00, 0x00,
}
