workspace:
  base: /go
  path: src/github.com/EVE-Tools/top-stations

pipeline:
  build:
    image: golang:alpine3.7
    commands:
      - apk update
      - apk add git
      - go get ./...
      - go build

  docker:
    image: plugins/docker
    repo: evetools/top-stations
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}